Numpy is a package to create, store and manipulate data. This is also the foundation that Pandas. We import a library using the 'import' keyword as numpy's common abbreviation is np

In [1]:
import numpy as np
import math

# Indexing Arrays

That techinque allow select data based on conditions, and copy or update data.

1. In  one-dimensional array, indexing works in similar ways as a list - To get an element in a one-dimensional array, we simply use the offset index.

2. In multidimensional array, if we want to select one certain element, we have to entering the index, which is comprised of two integers the first being the row, and the second the column

3. To get multiple elements and put them into a one-dimensional array, enter the indices directly into an array function.

4. Another form is use another form of array indexing, which essentiall "zips" the first list and the second list up

The index also works for booleans arrays

In [12]:
print('----- (1) ONE DIMENSIONAL -----')
a = np.array([1,3,5,7])
print (a)
print('a[2]: ' + str(a[2]))
print('----- (2) MULTIDIMENSIONAL -----')
b = np.array([[1, 2], [3, 4], [5, 6]])
print (b)
print('b[1,1]: ' + str(b[1,1]))
print('----- (3) MULTIPLE ITEMS -----')
print(np.array([b[0, 0], b[1, 1], b[2, 1]]))
print('----- (4) MULTIPLE ITEMS -----')
print(b[[0, 1, 2], [0, 1, 1]])

----- (1) ONE DIMENSIONAL -----
[1 3 5 7]
a[2]: 5
----- (2) MULTIDIMENSIONAL -----
[[1 2]
 [3 4]
 [5 6]]
b[1,1]: 4
----- (3) MULTIPLE ITEMS -----
[1 4 6]
----- (4) MULTIPLE ITEMS -----
[1 4 6]
