Numpy is a package to create, store and manipulate data. This is also the foundation that Pandas. We import a library using the 'import' keyword as numpy's common abbreviation is np

In [2]:
import numpy as np
import math

# Array Operations
We can mathematical manipulation (addition, subtraction, square, exponents) as well as use boolean arrays, which are binary values. We can also do matrix manipulation such as product, transpose, inverse, and so forth.

We can do:

1. Arithmetic operators on array apply elementwise (support matrix as well)

In [6]:
a = np.array([10,20,30,40])
b = np.array([1, 2, 3,4])
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print('----- a - b -----')
print(a-b)
print('----- a * b -----')
print(a*b)
#if we want to do elementwise product, we use the "*" sign
print('----- A * B -----')
print(A*B)
#if we want to do matrix product, we use the "@" sign
print('----- A @ B -----')
print(A@B)
print('----- EXEMPLE -----') #convert farenheit to celsius knowing the formula for conversion is ((°F − 32) × 5/9 = °C)
farenheit = np.array([0,-10,-5,-15,0])
celcius = (farenheit - 31) * (5/9)
print(celcius)

----- a - b -----
[ 9 18 27 36]
----- a * b -----
[ 10  40  90 160]
----- A * B -----
[[2 0]
 [0 4]]
----- A @ B -----
[[5 4]
 [3 4]]
----- EXEMPLE -----
[-17.22222222 -22.77777778 -20.         -25.55555556 -17.22222222]


2. Boolean operator on an array expect a return for any element in the original, with True being emitted if it meets the condition and False oetherwise.

In [4]:
#If we want to get a boolean array to check celcius degrees that are greater than -20 degrees
celcius > -20

array([ True, False, False, False,  True])

3.  Functions to use on theyself such as  sum(), max(), min(), and mean()

In [8]:
a1 = np.array([[8.1, 10.2, 12.1], [14.4, 16.2, 18.3]])
print('----- ARRAY ------')
print(a1)
print('----- SUM ------')
print(a1.sum())
print('----- MAX ------')
print(a1.max())
print('----- MIN ------')
print(a1.min())
print('----- MEAN ------')
print(a1.mean())

----- ARRAY ------
[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
----- SUM ------
79.3
----- MAX ------
18.3
----- MIN ------
8.1
----- MEAN ------
13.216666666666667
