Numpy is a package to create, store and manipulate data. This is also the foundation that Pandas. We import a library using the 'import' keyword as numpy's common abbreviation is np

In [2]:
import numpy as np
import math

# Array Creation

Arrays are a list or list of lists and can be created through list as well. To an array, we can:

1. pass in a list as an argument in numpy array

2. pass in a list of lists in numpy array, to create a multi-dimensional array (matrix)

3. use the zeros function to make an array just with 0 when we want the format but we are not sure about the content

4. use the ones function to make an array just with 1 when we want the format but we are not sure about the content

5. use the random function to make an array just with random numbers

6. use the arrange (starting bound, ending bound, difference between each consecutive numbers) function for integer

7. use the linspace(starting bound, ending bound, total number of items you want) function for floats

8. use the reshape(row, column) combine with arrange or linspace

In [3]:
print('----- (1) LIST ARGUMENT -----')
a = np.array([1, 2, 3])
print(a)
print('----- (2) LIST OF LIST ARGUMENT -----')
b = np.array([[1,2,3],[4,5,6]])
print(b)
print('----- (3) ZEROS FUNCTION -----')
c = np.zeros((2,3))
print(c)
print('----- (4) ONES FUNCTION -----')
d = np.ones((2,3))
print(d)
print('----- (5) RANDOM FUNCTION -----')
e = np.random.rand(2,3)
print(e)
print('----- (6) ARRANGE FUNCTION -----')
f = np.arange(10, 50, 2) #every even number from ten (inclusive) to fifty (exclusive)
print(f)
print('----- (7) LINSPACE FUNCTION -----')
g = np.linspace(0, 2, 15) #15 numbers from 0 (inclusive) to 2 (inclusive)
print(g)
print('----- (8) RESHAPE FUNCTION -----')
h = np.arange(1,16,1).reshape(3,5) #15 elements, ranging from 1 to 15, with a dimension of 3X5
print(h)

----- (1) LIST ARGUMENT -----
[1 2 3]
----- (2) LIST OF LIST ARGUMENT -----
[[1 2 3]
 [4 5 6]]
----- (3) ZEROS FUNCTION -----
[[0. 0. 0.]
 [0. 0. 0.]]
----- (4) ONES FUNCTION -----
[[1. 1. 1.]
 [1. 1. 1.]]
----- (5) RANDOM FUNCTION -----
[[0.93627612 0.75003181 0.35093274]
 [0.01276235 0.33027409 0.71675378]]
----- (6) ARRANGE FUNCTION -----
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
----- (7) LINSPACE FUNCTION -----
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.        ]
----- (8) RESHAPE FUNCTION -----
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Another important information is that you can check some important infos such as:

1. Numbers of dimensions using ndim attribute

2. Lenght of each dimension using shape attribute (return a tupple)

3. Type of items

In [3]:
print('----- (1) DIMENSIONS -----')
print(g.ndim)
print('----- (2) SHAPE -----')
print(g.shape)
print('----- (3) TYPE -----')
print(g.dtype)

----- (1) DIMENSIONS -----
1
----- (2) SHAPE -----
(15,)
----- (3) TYPE -----
float64
