Numpy is a package to create, store and manipulate data. This is also the foundation that Pandas. We import a library using the 'import' keyword as numpy's common abbreviation is np

In [5]:
import numpy as np
import math

# Slicing

It us a way to create a sub-array based on the original array. 

1. For one-dimensional arrays, slicing works in similar ways to a list. To slice, we use the : sign.


In [10]:
a = np.array([0,1,2,3,4,5]) 
print ('----- ARRAY -----')
print(a)
print ('----- a[:3] -----')
print(a[:3]) #put :3 in the indexing brackets and get elements from index 0 to index 3 (excluding index 3)
print ('----- a[2:4] -----')
print(a[2:4]) #put 2:4 in the bracket and get elements from index 2 to index 4 (excluding index 4)

----- ARRAY -----
[0 1 2 3 4 5]
----- a[:3] -----
[0 1 2]
----- a[2:4] -----
[2 3]


2. For multi-dimensional arrays, it works similarly.The first argument is for selecting rows and the second argument is for selecting columns

In [15]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print ('----- ARRAY -----')
print(b)
print ('----- b[:2] -----')
print (b[:2]) #put b[:2] then we would get all the elements from the first (0th) and second row (1th)
print ('----- b[:2, 1:3] -----')
print(b[:2, 1:3]) #put b[:2, 1:3], we get the first two rows but then thesecond and third column values only

----- ARRAY -----
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----- b[:2] -----
[[1 2 3 4]
 [5 6 7 8]]
----- b[:2, 1:3] -----
[[2 3]
 [6 7]]


Realize that a slice of an array is a view into the same data (this is called passing by reference). So modifying the sub array will consequently modify the original array.

In [16]:
#Here I'll change the element at position [0, 0], which is 2, to 50, then we can see that the value in the original array is changed to 50 as well
print ('----- ARRAY -----')
print(b)
sub_array = b[:2, 1:3]
print("sub array index [0,0] value before change:", sub_array[0,0])
sub_array[0,0] = 50
print("sub array index [0,0] value after change:", sub_array[0,0])
print("original array index [0,1] value after change:", b[0,1])
print ('----- ARRAY -----')
print(b)

----- ARRAY -----
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sub array index [0,0] value before change: 2
sub array index [0,0] value after change: 50
original array index [0,1] value after change: 50
----- ARRAY -----
[[ 1 50  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
